package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"stepbystep.com/m/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	var user User

	// Fetch the User to ensure it exists
	if err := r.Db.First(&user, "id = ?", input.UserID).Error; err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	todo := &model.Todo{
		ID:   uuid.NewString(),
		Text: input.Text,
		Done: false,
		User: &model.User{
			ID:   user.ID,
			Name: user.Name,
		},
	}

	if result := r.Db.Create(todo); result.Error != nil {
		return nil, result.Error
	}

	return todo, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, input string) (string, error) {
	var todo Todo
	if err := r.Db.First(&todo, "id = ?", input).Error; err != nil {
		return "", fmt.Errorf("todo not found: %w", err)
	}

	if err := r.Db.Delete(&todo).Error; err != nil {
		return "", fmt.Errorf("unable to delete todo: %w", err)
	}

	return "deleted successfully", nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input model.UpdateTodo) (*model.Todo, error) {
	var todo Todo
	if err := r.Db.First(&todo, "id = ?", input.ID).Error; err != nil {
		return nil, fmt.Errorf("todo not found: %w", err) // Handle if the Todo does not exist
	}

	todo.Text = input.Text

	if err := r.Db.Save(&todo).Error; err != nil {
		return nil, fmt.Errorf("unable to update todo: %w", err)
	}

	return &model.Todo{
		ID:   todo.ID,
		Text: todo.Text,
		Done: false,
		User: &model.User{
			ID: todo.UserID,
		},
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	user := &model.User{
		ID:   input.ID,
		Name: input.Name,
	}

	if r.Db == nil {
		return nil, fmt.Errorf("no db")
	}
	result := r.Db.Create(user)
	if result.Error != nil {
		return nil, result.Error
	}

	return user, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	var todos []*Todo

	result := r.Db.Find(&todos)
	if result.Error != nil {
		return nil, fmt.Errorf("error querying todos: %w", result.Error)
	}

	if result.RowsAffected == 0 {
		return nil, fmt.Errorf("no rows returned")
	}

	var results []*model.Todo
	for _, todo := range todos {
		results = append(results, &model.Todo{
			ID:   todo.ID,
			Text: todo.Text,
			Done: todo.Done,
		})
	}

	return results, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
